### ISSUE TITLE
Need " How to Install " section in README.md

### ISSUE THREAD

**Issue by saurabhbhise16** [ADS-B-Military-Analytics/ADS-B-Military-Analytics#10]
Hello, I am willing to contribute to this project. It will be helpful for anyone like me if they find the section on _**how to build**_ the project the right way.
Thank you

**Comment by EMcNugget** [comment]
Install instructions are present in CONTRIBUTING.md, however I added a section to hopefully make that more clear.

**Comment by saurabhbhise16** [comment]
Yes I later found it
